### ISSUE TITLE
Gmail RFC822 Error

### ISSUE THREAD

**Issue by kjm960725** [osoftteam/googleQt#2]
Rfc822 format .

You should use it as below.

Subject: (UTF-8)   // Encoding error occurred
You must change.
Subject: =?utf-8?B? (Base64) =?

Content-Type: multipart/alternative // use "multipart/mixed"

**Comment by ykhodak** [comment]
are you suggesting changing this line:
rv += QString("Content-Type: multipart/alternative; boundary=\"%1\"\r\n\r\n").arg(boundary);

in SendMimeMessageArg::toRfc822
?
I will test it and let you know.
Thanks.
