### ISSUE TITLE
 error: conversion from ‘uint64_t’ {aka ‘long unsigned int’} to ‘const QVariant’ is ambiguous

### ISSUE THREAD

**Issue by ddayjohn** [osoftteam/googleQt#6]
Hello guys,

I try to build this library but failed with QVariant Conversion on uint64_t . How to fix this problem ?  

Qt : 5.12
GCC : 10.3

error: conversion from ‘uint64_t’ {aka ‘long unsigned int’} to ‘const QVariant’ is ambiguous
filter_mask << t->m_filter_mask;

Thanks in advance.

**Comment by ykhodak** [comment]
someone will look at it next week. can you provide full error? we want to identify source file. We didn't use gcc for a while, there could be issue there. thank you for report.

**Comment by ykhodak** [comment]
should be fixed now, just added typecast to qulonglong
